---
name: Build image

'on':
  push:
  workflow_dispatch:

jobs:
  build_matrix:
    name: Build execution matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build execution matrix
        id: matrix
        uses: drugscom/docker-matrix-action@v1

  build_image:
    name: Build ${{ matrix.image-name }}
    needs: build_matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build_matrix.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Log into container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish container image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
          push: true
          tags: ${{ matrix.tags }}
      - name: Notify Slack - Success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@9b583ecdaddaa28bede5a056d8d8c8ff0363d66f
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: deploy
          status: Published "${{ matrix.image-name }}"
          color: good
      - name: Notify Slack - Failure
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@9b583ecdaddaa28bede5a056d8d8c8ff0363d66f
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: deploy
          status: Failed to build "${{ matrix.image-name }}"
          color: danger
